sudo: required
dist: trusty

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/.npm
    - /home/travis/.nuget/packages
    - src/LondonTravel.Site/node_modules

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

install:
  - npm install -g npm@5.7.1
  - npm install -g gulp@3.9.1

script:
  - ./build.sh --restore-packages
