sudo: required
dist: xenial
language: csharp
mono: none

os:
  - linux

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/.npm
    - /home/travis/.nuget/packages
    - src/LondonTravel.Site/node_modules

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - gettext
    - google-chrome-stable
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

install:
  - npm install --global npm

script:
  - ./build.sh --restore-packages
