sudo: required
dist: xenial
language: csharp
mono: none

os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/.npm
    - /home/travis/.nuget/packages
    - src/LondonTravel.Site/node_modules

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
  chrome: stable

install:
  - npm install --global npm

script:
  - ./build.sh
