os: Visual Studio 2017
version: 1.0.{build}

environment:
  CLI_VERSION: 1.0.1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

cache:
  - src\LondonTravel.Site\node_modules
  - '%APPDATA%\npm\node_modules'
  - '%APPDATA%\npm-cache'

install:
  - ps: npm install -g npm@4.5.0 --loglevel=error
  - ps: npm install -g gulp@3.9.1 --loglevel=error

build_script:
  - ps: .\Build.ps1

artifacts:
  - path: artifacts\publish

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
