os: Visual Studio 2019
version: 3.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

cache:
  - src\LondonTravel.Site\node_modules
  - '%APPDATA%\npm\node_modules'
  - '%APPDATA%\npm-cache'

install:
  - ps: npm install --global npm
  - ps: choco upgrade googlechrome --confirm --ignore-checksums --no-progress

build_script:
  - ps: .\build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\coverage.cobertura.xml"

artifacts:
  - path: artifacts\publish
  - path: artifacts\coverage*.xml
  - path: artifacts\*.png

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
