os: Visual Studio 2017
version: 2.2.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

cache:
  - src\LondonTravel.Site\node_modules
  - '%APPDATA%\npm\node_modules'
  - '%APPDATA%\npm-cache'

install:
  - ps: npm install -g npm
  - ps: npm install -g gulp@3.9.1 --loglevel=error
  - ps: choco upgrade googlechrome --confirm --no-progress

build_script:
  - ps: .\Build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\code-coverage.xml"

artifacts:
  - path: artifacts\publish
  - path: artifacts\code-coverage.xml
  - path: artifacts\*.png

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
