os: Visual Studio 2015
version: 1.0.{build}

environment:
  CLI_VERSION: 1.0.0-rc4-004788
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

install:
  - ps: npm install -g bower --loglevel=error
  - ps: npm install -g gulp --loglevel=error

build_script:
  - ps: .\Build.ps1

artifacts:
  - path: artifacts\publish

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
